micronaut:
  application:
    name: graphqlCatApi

graphql:
  enabled: true

  graphiql:
    enabled: true
    path: /graphiql
    page-title: GraphiQL

endpoints:
  loggers:
    enabled: true
    write-sensitive: false
